### ISSUE TITLE
Fatal Error on Compilation page.

### ISSUE THREAD

**Issue by mukundthanki** [fbrnc/Aoe_ClassPathCache#13]
Hi,

Nice extension.

I have installed it on site, when I visit System > Tools > Compilation page I see this Fatal error, "Undefined class constant 'SCOPE_FILE_PREFIX'" on this path "app/code/core/Mage/Compiler/Model/Process.php on line 259"

I have tested same in fresh magento with sample data, and error occurred there as well.

Will this affect site in anyway ? or should I ignore it ?

Everything else work fine and site speed increases drastically. I have one more question, how it will re-cache the class paths if I add new module ? will it do automatically ?

thanks alot for your time.

**Comment by twosg** [comment]
Same here

**Comment by fbrnc** [comment]
Hello everybody,
sorry for the confusion here. This repo (https://github.com/fbrnc/Aoe_ClassPathCache) is outdated. Please use this one: https://github.com/aoepeople/Aoe_ClassPathCache.

This specific issue was already fixed there.

Cheers,
Fabrizio
